### PR TITLE
Declare that enum casting returns an instance of the enum itself

### PR DESCRIPTION
**Pull request by hailwood**
In preparation for https://github.com/barryvdh/laravel-ide-helper/pull/1103

### CODE REVIEW

**Comment by slavarazum** [comment]
As I understood, it should be declared just return type.
Do we need other docblocks and will it work with native return typing?

**Comment by hailwood** [comment]
If you declare using native types that it returns an instance of itself the IDEhelper will docblock that will work.

However you'd need to declare that method in every extending enum (that's what I'm presently doing via @method).

But also using native types is a breaking change, a docblock update is no real change at all 👍

**Comment by slavarazum** [comment]
Why params are also need to be declared in docblock?

**Comment by hailwood** [comment]
Completion.

Many IDEs will complain that "parameter X is not documented". It doesn't affect the function here.

**Comment by slavarazum** [comment]
Most modern IDEs can take types from native declaration. I don't think that we should support IDEs which can't do it.

**Pull request closed without merging**
